default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: pguser
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planning_poke_development

test:
  <<: *default
  database: planning_poke_test
